# Generated by Django 4.2.7 on 2023-11-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='google_cid',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='outscraper_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
