# Generated by Django 4.2.7 on 2023-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_google_cid_company_outscraper_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='outscrapertask',
            name='was_processed',
            field=models.BooleanField(default=True),
        ),
    ]
