# Generated by Django 4.2.7 on 2023-11-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_outscrapertask_was_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outscrapertask',
            name='was_processed',
            field=models.BooleanField(default=False),
        ),
    ]
